services:
  - type: web
    name: fuzzer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./fuzzer_requests.db
      - key: PYTHON_VERSION
        value: 3.11.11 